<?php

namespace App\Console\Commands;

use App\Models\User;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use  App\Services\DataScraperService;

class api extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'api {action?}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        // if action is not provided, show help
        if(!$this->argument('action')){
            $this->info('Usage: php artisan api check <-- Check if scraper works and playwright is installed');
            $this->info('Usage: php artisan api create-user  <-- Create new user');
            $this->info('Usage: php artisan api setup  <-- Get token for user 1');
            $this->info('Usage: php artisan api trunkate-tokens <-- remove all tokens');
            return;
        }

        // create user
        if($this->argument('action') == 'create-user'){
            $this->info('Creating user...');
            //ask for user details
            $name = $this->ask('Enter name: ');
            $email = $this->ask('Enter email: ');
            $password = $this->secret('Enter password: ');

            $user = User::create([
                'name' => $name,
                'email' => $email,
                'password' => bcrypt($password),
            ]);
            $this->info('User created successfully');

            $api_user_token = $user->createToken('auth_token_autogenerated')->plainTextToken;
            $this->info('User token: '.$api_user_token);
            return;
        }

        // trunkate tokens
        if($this->argument('action') == 'trunkate-tokens'){
            $this->info('Trunkating tokens...');
            DB::table('personal_access_tokens')->truncate();
            $this->info('Tokens trunkated successfully');
            return;
        }

       // if command is crete
        if($this->argument('action') == 'setup'){
            $user = User::where('id', 1)->first();
            $api_user_token = $user->createToken('auth_token_autogenerated')->plainTextToken;

            // return only the token
            $api_user_token = explode('|', $api_user_token)[1];

            $this->info('User token: '.$api_user_token);
            $this->info('Save this token as it\'s only shown once');
        }

        // This command checks if playwright is installed and working on the system which allows our app to scrape data.
        if($this->argument('action') == 'check'){
           echo DataScraperService::checkIfScraperWorks();
        }

        if($this->argument('action') == 'load_courses_list'){
            DataScraperService::gatherCourses();
        }


        // if command is show auth_token_autogenerated
        if($this->argument('action') == 'table'){
            $json = DataScraperService::getTimetable("AL_KMOBA_8_4");
            dd($json);
        }
    }
}
